data:extend({
  {
    type = "item",
    icon = "__base__/graphics/icons/steel-chest.png",
    flags = {"goes-to-quickbar"},
    subgroup = "storage",
    order = "a[items]-c[steel-chest]",
    stack_size = 50,
    name = "nuclear-fission-reactor-chest-9",
    place_result = "nuclear-fission-reactor-chest-9",
  },
  {
    type = "item",
    icon = "__base__/graphics/icons/steel-chest.png",
    flags = {"goes-to-quickbar"},
    subgroup = "storage",
    order = "a[items]-c[steel-chest]",
    stack_size = 50,
    name = "nuclear-fission-reactor-chest-12",
    place_result = "nuclear-fission-reactor-chest-12",
  },
  {
    type = "item",
    icon = "__base__/graphics/icons/steel-chest.png",
    flags = {"goes-to-quickbar"},
    subgroup = "storage",
    order = "a[items]-c[steel-chest]",
    stack_size = 50,
    name = "nuclear-fission-reactor-chest-15",
    place_result = "nuclear-fission-reactor-chest-15",
  },
  {
    type = "item",
    icon = "__base__/graphics/icons/steel-chest.png",
    flags = {"goes-to-quickbar"},
    subgroup = "storage",
    order = "a[items]-c[steel-chest]",
    stack_size = 50,
    name = "nuclear-fission-reactor-chest-18",
    place_result = "nuclear-fission-reactor-chest-18",
  },
  {
    type = "item",
    icon = "__base__/graphics/icons/steel-chest.png",
    flags = {"goes-to-quickbar"},
    subgroup = "storage",
    order = "a[items]-c[steel-chest]",
    stack_size = 50,
    name = "nuclear-fission-reactor-chest-16",
    place_result = "nuclear-fission-reactor-chest-16",
  },
  {
    type = "item",
    icon = "__base__/graphics/icons/steel-chest.png",
    flags = {"goes-to-quickbar"},
    subgroup = "storage",
    order = "a[items]-c[steel-chest]",
    stack_size = 50,
    name = "nuclear-fission-reactor-chest-20",
    place_result = "nuclear-fission-reactor-chest-20",
  },
  {
    type = "item",
    icon = "__base__/graphics/icons/steel-chest.png",
    flags = {"goes-to-quickbar"},
    subgroup = "storage",
    order = "a[items]-c[steel-chest]",
    stack_size = 50,
    name = "nuclear-fission-reactor-chest-24",
    place_result = "nuclear-fission-reactor-chest-24",
  },
  {
    type = "item",
    icon = "__base__/graphics/icons/steel-chest.png",
    flags = {"goes-to-quickbar"},
    subgroup = "storage",
    order = "a[items]-c[steel-chest]",
    stack_size = 50,
    name = "nuclear-fission-reactor-chest-25",
    place_result = "nuclear-fission-reactor-chest-25",
  },
  {
    type = "item",
    icon = "__base__/graphics/icons/steel-chest.png",
    flags = {"goes-to-quickbar"},
    subgroup = "storage",
    order = "a[items]-c[steel-chest]",
    stack_size = 50,
    name = "nuclear-fission-reactor-chest-30",
    place_result = "nuclear-fission-reactor-chest-30",
  },
  {
    type = "item",
    icon = "__base__/graphics/icons/steel-chest.png",
    flags = {"goes-to-quickbar"},
    subgroup = "storage",
    order = "a[items]-c[steel-chest]",
    stack_size = 50,
    name = "nuclear-fission-reactor-chest-36",
    place_result = "nuclear-fission-reactor-chest-36",
  }
})